# Generated by Django 3.1.8 on 2021-04-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210415_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home_page_CTA_button',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_page_background_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_page_cta_button_label',
        ),
    ]
