# Generated by Django 3.1.8 on 2021-04-15 10:48

import blocks.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210415_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='homepage_content',
            field=wagtail.core.fields.StreamField([('navbar', wagtail.core.blocks.StructBlock([('nav_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('navbar_link_text_1', wagtail.core.blocks.CharBlock(help_text='Name of Art Piece', max_length=40, required=True)), ('navbar_link_1', wagtail.core.blocks.PageChooserBlock(required=False)), ('navbar_link_text_2', wagtail.core.blocks.CharBlock(help_text='Name of Art Piece', max_length=40, required=True)), ('navbar_link_2', wagtail.core.blocks.PageChooserBlock(required=False)), ('navbar_link_text_3', wagtail.core.blocks.CharBlock(help_text='Name of Art Piece', max_length=40, required=True)), ('navbar_link_3', wagtail.core.blocks.PageChooserBlock(required=False))])))])), ('homepage_cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('cta_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=40, required=False))])), ('home_page_title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add a title', required=False)), ('text', wagtail.core.blocks.TextBlock(help_text='Additional Text', required=False))])), ('home_page_subtitle', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add a title', required=False)), ('text', wagtail.core.blocks.TextBlock(help_text='Additional Text', required=False))])), ('home_page_description', blocks.blocks.RichtextBlock()), ('home_page_background_image', wagtail.images.blocks.ImageChooserBlock()), ('art_cards', wagtail.core.blocks.StructBlock([('gallery_block_title', wagtail.core.blocks.RichTextBlock(required=True)), ('art_cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title_of_picture', wagtail.core.blocks.CharBlock(help_text='Name of Art Piece', max_length=40, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('picture_description', wagtail.core.blocks.RichTextBlock(max_length=200, required=True)), ('button_to_site_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_to_external_URL', wagtail.core.blocks.URLBlock(help_text='Here, you can link to an external website', required=False)), ('button_text', wagtail.core.blocks.CharBlock(help_text='Text that will be displayed on the button', max_length=25, required=True))])))]))], blank=True, null=True),
        ),
    ]
