# Generated by Django 3.1.8 on 2021-04-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0061_auto_20210407_1453'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0006_homepage_all_block_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('navbar_link_text_1', models.CharField(blank=True, default='Nav Text 1', help_text='Navbar Text', max_length=25, null=True)),
                ('navbar_link_text_2', models.CharField(blank=True, default='Nav Text 2', help_text='Navbar Text', max_length=25, null=True)),
                ('navbar_link_text_3', models.CharField(blank=True, default='Nav Text 3', help_text='Navbar Text', max_length=25, null=True)),
                ('navbar_link_text_4', models.CharField(blank=True, default='Nav Text 4', help_text='Navbar Text', max_length=25, null=True)),
                ('navbar_link_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('navbar_link_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('navbar_link_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('navbar_link_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('navbar_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Navbar',
            },
            bases=('wagtailcore.page',),
        ),
    ]
