# Generated by Django 3.1.8 on 2021-04-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0061_auto_20210407_1453'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0007_navbar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navbar',
        ),
    ]
